name: Remove merged review app

on:
  pull_request:
    types: [closed]
    paths:
      - lib/**

permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - uses: EndBug/add-and-commit@v9
        with:
          remove: ./${{ github.head_ref }}
          message: "Remove ${{ github.head_ref }}"
