name: Build flutter web

on:
  pull_request:
    paths:
      - lib/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Flutter version
        id: get-flutter-version
        uses: zgosalvez/github-actions-get-flutter-version-env@v1
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.get-flutter-version.outputs.version }}
          cache: true
      - name: Cache pubspec dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: build-pubspec-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            build-pubspec-
      - name: Generate Dart config file
        run: flutter pub run videoapp:config
      - name: Build widgetbook for web
        run: flutter build web -t lib/main.dart
