name: Build main app

on:
  push:
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: https://vikmind.github.io/fldeploy//?sha=${{ github.sha }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Flutter version
        id: get-flutter-version
        uses: zgosalvez/github-actions-get-flutter-version-env@v1
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.get-flutter-version.outputs.version }}
          cache: true
      - name: Cache pubspec dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: build-pubspec-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            build-pubspec-
      - name: Build flutter web
        run: flutter build web -t lib/main.dart --base-href /fldeploy/
      - name: Deploy 🚀
        id: github-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web